services:
  - type: web
    name: worknest-api-raushancu1499
    runtime: docker
    plan: free
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://*.vercel.app
      - key: APP_JWT_SECRET
        generateValue: true
